update: deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -99,17 +99,15 @@ jobs:
           
           echo "Getting Docker Hub credentials..."
 
-          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
+          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:alelex10/backend-crm:pull" -u "alelex10:${{ secrets.DOCKERHUB_TOKEN }}" | jq -r '.token')
 
-          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ secrets.DOCKERHUB_USERNAME}}/${{ secrets.REPO_NAME }}:pull" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | jq -r '.token')
+          curl -s -H "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/alelex10/backend-crm/tags/list"
 
-          curl -s -H "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}/tags/list" | jq . | jq -r '.tags[]'
-
-          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
-          if [ -z "$HUB_TOKEN" ]; then
-            echo "Error: No se pudo obtener el token de autenticación."
-            exit 1
-          fi
+          # HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
+          # if [ -z "$HUB_TOKEN" ]; then
+          #   echo "Error: No se pudo obtener el token de autenticación."
+          #   exit 1
+          # fi
 
           echo "Token de autenticación obtenido ${HUB_TOKEN} and ${AUTH_TOKEN}"
 
