update: deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -96,25 +96,24 @@ jobs:
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
           DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
-
         run: |
           KEEP=5
           REPO="alelex10/backend-crm"
           
           echo "Getting Docker Hub credentials..."
 
-          AUTH_TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:pull" \
-            -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | jq -r '.token')
-          if [ -z "$AUTH_TOKEN" ]; then
-            echo "Error: No se pudo obtener el token de autenticación."
-            exit 1
-          fi
+          # AUTH_TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.REPO_NAME }}:pull" \
+          #   -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | jq -r '.token')
+          # if [ -z "$AUTH_TOKEN" ]; then
+          #   echo "Error: No se pudo obtener el token de autenticación."
+          #   exit 1
+          # fi
 
-          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
-          if [ -z "$HUB_TOKEN" ]; then
-            echo "Error: No se pudo obtener el token de autenticación."
-            exit 1
-          fi
+          # HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
+          # if [ -z "$HUB_TOKEN" ]; then
+          #   echo "Error: No se pudo obtener el token de autenticación."
+          #   exit 1
+          # fi
 
           echo "Token de autenticación obtenido"
 
