update: deploy file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -84,7 +84,7 @@ jobs:
               -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
               -e JWT_SALT_ROUNDS='${{ secrets.JWT_SALT_ROUNDS }}' \
               --name $CONTAINER_NAME -p $CONTAINER_PORT:3000 --restart unless-stopped $IMAGE
-              
+
   cleanup-old-images:
     runs-on: ubuntu-latest
     needs: build-and-push
@@ -96,14 +96,31 @@ jobs:
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
           DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
+
         run: |
           KEEP=5
           REPO="alelex10/backend-crm"
-          echo "🔍 Getting tags for $REPO..."
-          TAGS=$(curl -s -u $DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN \
-            "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" \
-            | jq -r '.results[].name' | grep -v latest | sort)
           
+          echo "Getting Docker Hub credentials..."
+
+          AUTH_TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${HUB_USERNAME}/${REPO_NAME}:pull" \
+            -u "${HUB_USERNAME}:${HUB_PASSWORD}" | jq -r '.token')
+          if [ -z "$AUTH_TOKEN" ]; then
+            echo "Error: No se pudo obtener el token de autenticación."
+            exit 1
+          fi
+
+          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
+          if [ -z "$HUB_TOKEN" ]; then
+            echo "Error: No se pudo obtener el token de autenticación."
+            exit 1
+          fi
+
+          echo "Token de autenticación obtenido"
+
+          echo "🔍 Getting tags for $REPO..."
+          TAGS=$(curl -s -H "Authorization: Bearer $AUTH_TOKEN" "https://registry-1.docker.io/v2/${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}/tags/list" | jq -r '.tags[]')
+
           COUNT=$(echo "$TAGS" | wc -l)
           echo "Found $COUNT tags"
 
@@ -111,10 +128,11 @@ jobs:
             DELETE_TAGS=$(echo "$TAGS" | head -n -$KEEP)
             for tag in $DELETE_TAGS; do
               echo "🗑️ Deleting $tag..."
-              curl -s -X DELETE -u $DOCKERHUB_USERNAME:$DOCKERHUB_TOKEN \
-                "https://hub.docker.com/v2/repositories/$REPO/tags/$tag/"
+              curl -i -X DELETE \
+                -H "Accept: application/json" \
+                -H "Authorization: JWT $HUB_TOKEN" \
+                https://hub.docker.com/v2/repositories/alelex10/backend-crm/tags/c6ddf45a/
             done
           else
             echo "No tags to delete."
           fi
-
