update: deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -101,13 +101,13 @@ jobs:
 
           TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ secrets.DOCKERHUB_USERNAME }}/backend-crm:pull" -u "${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }}" | jq -r '.token')
 
-          TAGS=$(curl -s -H "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/alelex10/${{ secrets.CONTAINER_NAME }}/tags/list" | jq -r '.tags[]')
+          TAGS=$(curl -s -H "Authorization: Bearer $TOKEN" "https://registry-1.docker.io/v2/${{secrets.DOCKERHUB_USERNAME}}/${{ secrets.CONTAINER_NAME }}/tags/list" | jq -r '.tags[]')
 
-          # HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
-          # if [ -z "$HUB_TOKEN" ]; then
-          #   echo "Error: No se pudo obtener el token de autenticación."
-          #   exit 1
-          # fi
+          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKERHUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKERHUB_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
+          if [ -z "$HUB_TOKEN" ]; then
+            echo "Error: No se pudo obtener el token de autenticación."
+            exit 1
+          fi
 
           # echo "Token de autenticación obtenido ${HUB_TOKEN} and ${TOKEN}"
 
@@ -116,8 +116,8 @@ jobs:
           # echo "Listando etiquetas para ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.CONTAINER_NAME }}..."
           
           
-          # COUNT=$(echo "$TAGS" | wc -l)
-          # echo "Found $COUNT tags"
+          COUNT=$(echo "$TAGS" | wc -l)
+          echo "Found $COUNT tags"
 
           # if [ "$COUNT" -gt "$KEEP" ]; then
           #   DELETE_TAGS=$(echo "$TAGS" | head -n -$KEEP)
